apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gi
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle    # override StorageClass reclaimPolicy
  storageClassName: fake-ssd
  hostPath:
    path: /tmp
